### PR TITLE
chore: Update Showcase to the latest released version, 0.16.0

### PR DESCRIPTION
**Pull request by vchudnov-g**

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]

**Review by software-dov — COMMENTED** [review]
I think we can just delete the circleci configs instead of keeping them updated.

I'm very confused about the errors as well.

**Comment by arithmetic1728** [comment]
> I think we can just delete the circleci configs instead of keeping them updated.
> 
> I'm very confused about the errors as well.

Yes, that works for me.

**Comment by vchudnov-g** [comment]
@software-dov @busunkim96 Do these sound like spurious failures? All checks passed before merging master....

**Comment by vchudnov-g** [comment]
So it looks like we're failing because the generated Showcase GAPIC has 0% code coverage, I guess because it doesn't have unit tests (?). I'm confused why this wasn't a problem before this PR.

Suggestions?

**Comment by software-dov** [comment]
Took a look at the failing CI, and I believe that the code cov failure is possibly a red herring. The tests definitely run locally, definitely run in CI, but the coverage isn't being tracked correctly.

**Comment by software-dov** [comment]
The update made it's way in via another PR. @vchudnov-g mind if we close this?

**Comment by vchudnov-g** [comment]
Yes. let's close this, since this was done in #925

**Pull request closed without merging**
