### PR TITLE
chore: drop use of deprecated 'distutils.util.strtobool'

### LINKED ISSUE #1007: Use of 'distutils.utils.strtobool' generates DeprecationWarning under Python 3.10
```bash
$ nox -re unit-3.10
...
google/cloud/firestore_admin_v1/services/firestore_admin/client.py:17
  /home/tseaver/projects/agendaless/Google/src/python-firestore/google/cloud/firestore_admin_v1/services/firestore_admin/client.py:17: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils import util
...
```

### PR DESCRIPTION
**Pull request by parthea**
Fixes #1007

### CODE REVIEW

**Comment by software-dov** [comment]
Go for it.

**Comment by parthea** [comment]
@software-dov friendly ping

**Comment by parthea** [comment]
This is ready for review.

**Review by tseaver — APPROVED** [review]
I started to suggest that the same check-and-raise logic be added for the `GAPIC_PYTHON_ASYNC` envvar.  Did you decide not to bother because the only place where we expect that one to be set is in the CI configs for this repo?  Versus the ones in generated-from-templates files, where users might be setting them?

**Pull request merged**
