### PR TITLE
chore: allow 'google-api-core' 2.x versions

### LINKED ISSUE #955: Expand range for 'google-api-core to allow 2.x versions

### PR DESCRIPTION
**Pull request by tseaver**
Closes #955.

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]
LGTM - could you make the same change in the Ads Templates?

**Comment by tseaver** [comment]
@busunkim96 I've updated to include `gapic/ads-template/setup.py.j2`.  Do I need to update the `tests/integration/goldesns` versions too?

**Comment by busunkim96** [comment]
Ah looks like it. You can change those manually or through bazel (instructions are [here](https://github.com/googleapis/gapic-generator-python/blob/master/DEVELOPMENT.md#integration-tests))

**Comment by tseaver** [comment]
@busunkim96 The integration tests fail locally for me on `master` (same on this branch), e.g.:

```bash
$ bazel test //tests/integration:asset
...
ERROR: .../gapic-generator-python/BUILD.bazel:52:10: no such package '@gapic_generator_python_pip_deps//pypi__googleapis_common_protos': BUILD file not found in directory 'pypi__googleapis_common_protos' of external repository @gapic_generator_python_pip_deps. Add a BUILD file to a directory to mark it as a package. and referenced by '//:gapic_plugin'
ERROR: Analysis of target '//tests/integration:asset' failed; build aborted: Analysis failed
INFO: Elapsed time: 25.034s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (31 packages loaded, 329 targets c\
FAILED: Build did NOT complete successfully (31 packages loaded, 329 targets c\
onfigured)
    currently loading: @com_github_grpc_grpc//src/python/grpcio/grpc
    Fetching @local_config_cc; fetching
```

I can't see the actual failure output in the Github action (the `.log` files under `~/.cache/bazel/`), which makes debugging particularly hard.

**Comment by tseaver** [comment]
@busunkim96 Thank you!

**Pull request merged**
