### PR TITLE
feat: Add typing to proto.Message based class attributes

### LINKED ISSUE #1379: Fix attribute types for autogenerated protobuf classes
## Issue

- The autogenerated protobuf classes are of the following form:
  ```python
  class ProtobufClass(proto.Message):
      """...
      Attributes:
          # Primitive types
          attribute_1 (str):...
          attribute_2 (int):...
          attribute_3 (float):...
          ...
          # Compound types
          attribute_A (TYPE_A):...
          attribute_B (Sequence[TYPE_B]):...
          attribute_C (Mapping[KEY_TYPE_C, VALUE_TYPE_C]):...
      """
      attribute_1 = proto.Field(proto.STRING, number=1)
      attribute_2 = proto.Field(proto.INT32, number=2)
      attribute_3 = proto.Field(proto.FLOAT, number=3)
      ...
      attribute_A = proto.Field(proto.MESSAGE, number=4, message="TYPE_A")
      attribute_B = proto.RepeatedField(proto.MESSAGE, number=5, message="TYPE_B")
      attribute_C = proto.MapField(...)
      ...
  ```
  - ✔️ The docstrings seem perfectly correct (they match the actual types at runtime).
  - ❌ The attributes indicate protobuf types (always `proto.Field` `proto.RepeatedField`, or `proto.MapField`?).
- As a consequence, type checkers (e.g. pyright) can report issues such as:
  - ```
    Cannot access member "MEMBER" for type "Field"
    Member "MEMBER" is unknown
    ```
  - ```
    Expression of type "Field" cannot be assigned to return type "TYPE"
    "Field" is incompatible with "TYPE"
    ```
  - ```
    "RepeatedField" is not iterable
    "__iter__" method not defined
    ```
  - ```
    Argument of type "RepeatedField" cannot be assigned to parameter "__obj" of type "Sized" in function "len"
    "RepeatedField" is incompatible with protocol "Sized"
    "__len__" is not present
    ```

## Proposal

- Adding type annotations at the attribute level (`attribute_X: TYPE_X = proto.*`) may consistently fix these type checker issues.
- In a nutshell, here is what it could look like:
  ```python
  class ProtobufClass(proto.Message):
      """...
      Attributes:
          attribute_1 (TYPE_1):...
          attribute_2 (TYPE_2):...
          attribute_3 (Sequence[TYPE_3]):...
          attribute_4 (Mapping[KEY_TYPE_4, VALUE_TYPE_4]):...
      """
      attribute_1: TYPE_1 = proto.Field(proto.PRIMITIVE_PROTO_TYPE, number=1)
      attribute_2: TYPE_2 = proto.Field(proto.MESSAGE, number=2, message="TYPE_2")
      attribute_3: Sequence[TYPE_3] = proto.RepeatedField(proto.MESSAGE, number=3, message="TYPE_3")
      attribute_4: Mapping[KEY_TYPE_4, VALUE_TYPE_4] = proto.MapField(...)
      ...
  ```

## Why is it an issue

- It's likely to generate more and more friction as static type checking becomes the norm (+ the numbers of users and client libraries keep increasing).
- Some client libraries are pretty large (e.g. [google.cloud.documentai.Document](https://github.com/googleapis/python-documentai/blob/main/google/cloud/documentai_v1/types/document.py)) and IDE autocompletion is a must-have.
- This can lead developers to add unnecessary boilerplate (e.g. `typing.TypeAlias`) or casting (e.g. `typing.cast` or worse).
- This has already been reported: [SA#73126100](https://stackoverflow.com/questions/73126100/pyright-identifies-type-as-field-and-not-str) & [gapic-generator-python#694](https://github.com/googleapis/gapic-generator-python/issues/694).

### PR DESCRIPTION
**Pull request by PicardParis**
Fixes #1379

### CODE REVIEW

**Comment by PicardParis** [comment]
Here is the rationale for the latest changes:
1. `proto.RepeatedField` 
   - The runtime type is `proto.marshal.collections.repeated.RepeatedComposite`
   - `RepeatedComposite` is a subclass of `MutableSequence`:
     - `class Repeated(collections.abc.MutableSequence): ...`
     - `class RepeatedComposite(Repeated): ...`
   - See [implementation](https://github.com/googleapis/proto-plus-python/blob/5001b6f176b394956f4aa9073a24e717a02011ff/proto/marshal/collections/repeated.py#L83)
2. `proto.MapField` 
   - The runtime type is `proto.marshal.collections.maps.MapComposite`
   - `MapComposite` is a subclass of `MutableMapping`:
     - `class MapComposite(collections.abc.MutableMapping): ...`
   - See [implementation](https://github.com/googleapis/proto-plus-python/blob/5001b6f176b394956f4aa9073a24e717a02011ff/proto/marshal/collections/maps.py#L21)
3. Parts of the code do use these attributes as mutable:
   - Example: https://github.com/googleapis/gapic-generator-python/blob/1a948434e32baf180426ef35d2cc8ce05628d001/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/async_client.py.j2#L305
4. Doc annotations incorrectly indicated `Sequence` & `Mapping`
   - See [implementation](https://github.com/googleapis/gapic-generator-python/blob/1a948434e32baf180426ef35d2cc8ce05628d001/gapic/schema/metadata.py#L366)
5. Goal of the changes: `Sequence` → `MutableSequence` & `Mapping` → `MutableMapping`

**Comment by parthea** [comment]
I'm going to close and re-open this PR to re-trigger gh actions.

**Review by parthea — APPROVED** [review]

**Comment by PicardParis** [comment]
...fixing conflicts due to updates in the main branch...

**Review by parthea — CHANGES_REQUESTED** [review]
I generated the code locally for datastore and the mypy test failed with these changes.
See generated code here: https://github.com/googleapis/python-datastore/compare/test-local-gapic?expand=1

**Comment by PicardParis** [comment]
- I made another pass. Tests are successful.
- I was not able to reproduce your issue when generating datastore locally.
  - We must be using different generation commands.
  - I tried
    ```
    protoc google/datastore/v1/*.proto \
      --proto_path=../api-common-protos/ --proto_path=. \
      --python_gapic_out=../dest/
    ```
    and
    ```
    protoc google/datastore/admin/v1/*.proto \
      --proto_path=../api-common-protos/ --proto_path=. \
      --python_gapic_out=../dest/
    ```
    and `nox -s mypy` completes for both.
  - Which command do you use to generate datastore?
- Anyway, the new pass should be exhaustive. Can you recheck?

**Review by parthea — APPROVED** [review]
LGTM

**Pull request merged**
