### PR TITLE
chore: use trim_blocks and lstrip_blocks for jinja templates

### PR DESCRIPTION
**Pull request by busunkim96**
Enable `trim_blocks` and `lstrip_blocks` in the Jinja environment to make it easier to manage whitespace and newlines. This PR may result in slight changes to the formatting of generated code.

https://jinja.palletsprojects.com/en/2.11.x/api/#jinja2.Environment
https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control

### CODE REVIEW

**Comment by software-dov** [comment]
How's the result?

**Comment by busunkim96** [comment]
@software-dov Still working out issues in a few places (hence the failing tests :)), but I think this should result in fewer instances of manual whitespace trimming `{%-}` and `{-%}`. https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control was the inspiration.

**Comment by software-dov** [comment]
More power to you for doing this. I remember having screaming fits when I first tried to make vaguely-python-whitespace templates.

**Review by software-dov — APPROVED** [review]

**Comment by busunkim96** [comment]
Will get #774 over the line first and then merge this, since I suspect there will be merge conflicts otherwise.

**Pull request merged**
